sudo: required

language: generic

services:
  - docker

install:
  - docker pull dxjoke/tectonic-docker

script:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic hackers-delight.tex"
  - mkdir gh-pages
  - cp {hackers-delight.pdf,index.html} gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: gh-pages
