sudo: required

language: generic

env:
  global:
    - TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}

services:
  - docker

before_install:
  - docker pull dxjoke/tectonic-docker

script:
  - docker run tectonic "$TRAVIS_REPO_NAME".tex

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  # Keep older versions to browse
  keep-history: true
  # Only publish master
  on:
    branch: master
