sudo: required

language: generic

services:
  - docker

install:
  - docker pull dxjoke/tectonic-docker

script:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic hackers-delight.tex"
  - cp hackers-delight.pdf gh-pages/hackers-delight.pdf

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: gh-pages
